//! ADR-016/017 follow-up — phantom collision against the GRID_GEN world (the world Unity
//! actually renders), replacing the historical world::generator path.
//!
//! The robapieles previously collided against `world::generator`'s `ChunkLayoutV1`, a DIFFERENT
//! generator from grid_gen. Since Unity renders grid_gen (via `tile_walls` → IPC chunk stream →
//! `GridChunkBuilder`), the phantom phased through visible walls and snagged on invisible ones.
//! This module resolves the phantom's movement against grid_gen's own 20×20 cell grid, generated
//! by the SAME deterministic path the render uses, so collision matches what the player sees.
//!
//! Host-only, on-demand, bounded cache; NEVER serialized to Unity and NEVER inserted into
//! `world.chunks`. The player collision path (`world::collision`) is untouched.
//!
//! GRANULARITY NOTE (D-colisión = (a) raw cells): this samples raw 2.5 m grid_gen cells
//! (`Cell::is_walkable`), which share the GENERATOR with the render but not its exact tile-walls
//! model (5 m tiles, every tile floored, walls only on the `tile_walls` bitmask edges). It removes
//! the wrong-WORLD mismatch; a small residual cell-vs-tile mismatch remains until/if collision
//! moves to the `tile_walls` bitmask (option (b), deferred).

use std::collections::HashMap;

use crate::utils::Vec3;

use super::{
    generate_chunk_layer, LayerGrid, LayerRules, CELL_SIZE_M, CHUNK_CELLS, LAYER_HEIGHT_M,
    LAYER_PROFILES,
};

/// World-units per chunk side (20 cells × 2.5 m = 50 m).
const CHUNK_SIZE_M: f32 = CELL_SIZE_M * CHUNK_CELLS as f32;
/// Max live cached grid_gen layouts; farthest-from-query eviction (mirrors `SimChunkCache`).
///
/// ADR-043 — DERIVED, not picked: an A\* window is 49 cells a side (`NAV_WINDOW_CELLS` = 24) over
/// 20-cell chunks, so one search touches up to 4×4 = **16 chunk-layers**. The old 64 was therefore
/// the working set of exactly FOUR movers — with a populated world, the fifth pushed the cache into
/// permanent mutual eviction, because `enforce_cap` evicts by distance from a SINGLE `center` (the
/// mover that just acted) and every mover discards the chunks of the previous one. 256 = 16 movers
/// of headroom, which the activation cap keeps well out of reach.
///
/// Cost is linear and small: a `LayerGrid` is `CHUNK_CELLS²` = 400 `Cell`s of 4 B = 1600 B, so the
/// full cache is ~420 KB. `cell_is_four_bytes_so_the_cache_budget_holds` pins the 4 B, which is a
/// `repr(Rust)` layout nobody had asserted.
///
/// Raising this WITHOUT raising the activation cap is safe; raising the activation cap without
/// raising this brings the thrash straight back. They are one decision in two constants.
pub const GRID_CACHE_MAX_CHUNKS: usize = 256;

/// Host-only, on-demand cache of grid_gen `LayerGrid`s for phantom collision. Generated by the
/// SAME deterministic call the render uses (`generate_chunk_layer(..., &[])`), so the phantom
/// collides against the geometry the player sees. Never serialized, never in `world.chunks`.
pub struct GridGenChunkCache {
    seed: u64,
    cache: HashMap<(i32, i32, u8), LayerGrid>,
    rules_fn: RulesFn,
    /// Absolute cells made impassable by something OUTSIDE the generator — today the player's own
    /// building pieces. Kept as an opaque set of cells on purpose: `grid_gen` must not learn what a
    /// building is (it may not import `world/`), and whoever owns that roster fills this in.
    ///
    /// It lives on the CACHE rather than being threaded through every signature so that collision
    /// and navigation cannot disagree: both already read the world through this object, so a wall
    /// you build is a wall the pathfinder plans around, not just one the phantom bumps into.
    blocked_cells: std::collections::HashSet<(i32, i32)>,
    /// ADR-043 — how many times this cache has had to run `generate_chunk_layer`. A cache that is
    /// doing its job answers from memory, so after warm-up this stops growing; if it keeps
    /// climbing, movers are evicting each other and every step pays full generation. It is the
    /// only way to SEE that thrash: the cache stays at its cap either way, so `len()` looks
    /// identical whether the contents are stable or churning completely every tick.
    generated: u64,
    /// ADR-043 — how many times the body-radius check has had to fall back to POINT sampling
    /// because the creature did not fit where it already stood (`resolve_move_grid_gen_ex`'s safety
    /// valve). The valve is not optional — without it a phantom in a tight spot is blocked in all
    /// four directions forever — but while it is engaged the body radius is off, which is the
    /// leading suspect for the intermittent wall-scraping. Counting it is what turns that from a
    /// hunch into something a single play-test can confirm or clear.
    degraded_body_checks: u64,
}

/// Resolutor de perfil por chunk: `(world_seed, cx, cz, layer) → LayerRules`.
///
/// ADR-033 inyecta aquí `world::zone_density::rules_for` (que deriva el perfil
/// del `zone_kind` del chunk) SIN que `grid_gen` importe `world/` — la
/// invariante del módulo se conserva porque grid_gen solo conoce la FIRMA, no
/// la implementación ni el concepto de zona.
pub type RulesFn = fn(u64, i32, i32, u8) -> LayerRules;

/// Resolutor por defecto: perfil de capa, el comportamiento pre-ADR-033.
///
/// Solo para consumidores que deliberadamente no quieren densidad por zona
/// (tests de generación pura). Las rutas de RENDER y ROBAPIELES deben inyectar
/// el resolutor real: si una usa este y la otra no, render y colisión divergen
/// — exactamente lo que ADR-033 promete que no pasa.
pub fn default_layer_rules(_seed: u64, _cx: i32, _cz: i32, layer: u8) -> LayerRules {
    LAYER_PROFILES[(layer as usize).min(LAYER_PROFILES.len() - 1)].clone()
}

impl GridGenChunkCache {
    /// Caché con el perfil de capa plano (sin densidad por zona).
    pub fn new(seed: u64) -> Self {
        Self::with_rules(seed, default_layer_rules)
    }

    /// Caché con resolutor de perfil explícito (ADR-033).
    pub fn with_rules(seed: u64, rules_fn: RulesFn) -> Self {
        Self {
            seed,
            cache: HashMap::new(),
            rules_fn,
            blocked_cells: std::collections::HashSet::new(),
            generated: 0,
            degraded_body_checks: 0,
        }
    }

    /// Cumulative `generate_chunk_layer` calls (see `generated`). Read by the host's throttled
    /// step instrumentation so a populated world can be measured instead of guessed.
    pub fn generated_count(&self) -> u64 {
        self.generated
    }

    /// Cumulative body-radius fallbacks to point sampling (see `degraded_body_checks`).
    pub fn degraded_body_check_count(&self) -> u64 {
        self.degraded_body_checks
    }

    /// Replace the externally-blocked cell set (see `blocked_cells`). Cheap to call on a cadence:
    /// the caller decides when its roster changed.
    pub fn set_blocked_cells(&mut self, cells: std::collections::HashSet<(i32, i32)>) {
        self.blocked_cells = cells;
    }

    pub fn blocked_cell_count(&self) -> usize {
        self.blocked_cells.len()
    }

    fn is_blocked_cell(&self, gx: i32, gz: i32) -> bool {
        self.blocked_cells.contains(&(gx, gz))
    }

    pub fn len(&self) -> usize {
        self.cache.len()
    }

    pub fn is_empty(&self) -> bool {
        self.cache.is_empty()
    }

    /// Seed a hand-authored grid so a test can reason about a known layout instead of a generated
    /// one. Test-only: production code must always come from `get_or_generate`, or nav and render
    /// could diverge (ADR-033).
    #[cfg(test)]
    pub(super) fn insert_for_test(&mut self, key: (i32, i32, u8), grid: LayerGrid) {
        self.cache.insert(key, grid);
    }

    /// The grid_gen `LayerGrid` for (cx, cz, layer), generated on first access with the same
    /// generator + EMPTY `forced_walkable` that `chunk_tile_walls` uses — so the cached grid is
    /// byte-identical to the rendered chunk's source. Since ADR-033 that identity ALSO requires
    /// the same `rules_fn` as the render path: `grid_cache_layout_matches_direct_generation`
    /// guards it.
    pub fn get_or_generate(&mut self, cx: i32, cz: i32, layer: u8) -> &LayerGrid {
        // Single hash lookup per access (was contains_key + insert + get = 3).
        let seed = self.seed;
        let rules_fn = self.rules_fn;
        let generated = &mut self.generated;
        self.cache.entry((cx, cz, layer)).or_insert_with(|| {
            *generated += 1;
            let rules = rules_fn(seed, cx, cz, layer);
            generate_chunk_layer(&rules, seed, (cx, cz), layer as i32, &[]).grid
        })
    }

    /// Evict the farthest-from-`center` (Chebyshev) layouts until within the cap. The current
    /// move's working set sits closest to `center`, so it is never evicted.
    pub fn enforce_cap(&mut self, center: (i32, i32)) {
        while self.cache.len() > GRID_CACHE_MAX_CHUNKS {
            let farthest = self
                .cache
                .keys()
                .max_by_key(|(cx, cz, _)| (cx - center.0).abs().max((cz - center.1).abs()))
                .copied();
            match farthest {
                Some(k) => {
                    self.cache.remove(&k);
                }
                None => break,
            }
        }
    }
}

/// World XZ → ABSOLUTE grid_gen cell index, unbounded in both directions. This is the single
/// quantization used by everything in this module (and, from ADR-040, by the navigation): deriving
/// the chunk-local form from it instead of re-deriving it separately is what stops a split-brain
/// where the collision and the pathfinder disagree about which cell a position is in.
pub(super) fn global_cell(pos: Vec3) -> (i32, i32) {
    (
        (pos.x / CELL_SIZE_M).floor() as i32,
        (pos.z / CELL_SIZE_M).floor() as i32,
    )
}

/// World XZ → (chunk_x, chunk_z, cell_x, cell_z) in grid_gen coords. Derived from `global_cell`;
/// `div_euclid`/`rem_euclid` handle negative world coordinates and put the local cell in 0..20 by
/// construction (the old explicit clamp is no longer reachable).
fn world_to_grid_cell(pos: Vec3) -> (i32, i32, usize, usize) {
    let (gx, gz) = global_cell(pos);
    let n = CHUNK_CELLS as i32;
    (
        gx.div_euclid(n),
        gz.div_euclid(n),
        gx.rem_euclid(n) as usize,
        gz.rem_euclid(n) as usize,
    )
}

/// Walkability of an ABSOLUTE cell, without going through a world position.
pub(super) fn cell_is_walkable(cache: &mut GridGenChunkCache, gx: i32, gz: i32, layer: u8) -> bool {
    // Player-built geometry first: it is not in the generator's output, so a cell the generator
    // calls open can still be occupied by something you put there.
    if cache.is_blocked_cell(gx, gz) {
        return false;
    }
    let n = CHUNK_CELLS as i32;
    cache
        .get_or_generate(gx.div_euclid(n), gz.div_euclid(n), layer)
        .get(gx.rem_euclid(n) as usize, gz.rem_euclid(n) as usize)
        .is_walkable()
}

/// ADR-040 D-DIAGONAL. True if a step that crosses a cell boundary on BOTH axes may be taken.
///
/// The old code accepted such a step on a single point sample of the DESTINATION, so a move from
/// (i,j) to (i+1,j+1) went through whichever of (i+1,j) / (i,j+1) the segment actually passes —
/// even when that cell is solid. That is the phantom walking through a wall, and it is frequent:
/// 470 pinch sites over 400 chunks of the production world (59.8 % of chunks).
///
/// The rule is EXACT rather than conservative. Both cheap approximations are wrong in a way you
/// would see in play: "block only if BOTH intermediates are solid" leaves the real hole open, and
/// "require BOTH walkable" forbids legally cutting a convex corner, which makes the creature move
/// in a stiff cross pattern. Since a step is shorter than one cell, exactly one boundary is crossed
/// per axis, so the segment enters exactly ONE intermediate cell: the one whose boundary is crossed
/// FIRST. An exact tie is the zero-width corner point and is refused.
pub(super) fn diagonal_step_is_clear(
    cache: &mut GridGenChunkCache,
    layer: u8,
    from: Vec3,
    to: Vec3,
) -> bool {
    let (fx, fz) = global_cell(from);
    let (tx, tz) = global_cell(to);
    if fx == tx || fz == tz {
        return true; // axial (or same cell): nothing between start and end
    }
    // Defensive: the caller guarantees sub-cell steps (frozen by
    // `max_phantom_step_stays_under_one_cell`). A longer jump would cross several intermediates and
    // this two-cell reasoning would be incomplete, so refuse it and let the axial slide handle it.
    if (tx - fx).abs() > 1 || (tz - fz).abs() > 1 {
        return false;
    }
    let dx = to.x - from.x;
    let dz = to.z - from.z;
    if dx == 0.0 || dz == 0.0 {
        return true; // no motion on an axis → not actually diagonal
    }
    // The boundary crossed on each axis: the higher index when moving +, the start index when -.
    let bx = tx.max(fx) as f32 * CELL_SIZE_M;
    let bz = tz.max(fz) as f32 * CELL_SIZE_M;
    let t_x = (bx - from.x) / dx;
    let t_z = (bz - from.z) / dz;
    if (t_x - t_z).abs() < 1e-5 {
        return false; // exact corner crossing: zero-width gap, never legal
    }
    let (mx, mz) = if t_x < t_z { (tx, fz) } else { (fx, tz) };
    cell_is_walkable(cache, mx, mz, layer)
}

/// Floor-plane Y of a grid_gen `layer` — the SAME pitch Unity renders (layer 0 = 0, layer 1 = 4,
/// layer 2 = 8, …).
pub fn grid_floor_y(layer: u8) -> f32 {
    layer as f32 * LAYER_HEIGHT_M
}

/// World Y → the macro layer that Y stands on (inverse of the layer pitch), clamped to the valid
/// layer range. Used to pick which grid_gen layer's cells a phantom collides against, derived from
/// its own pose Y so it works on every layer without a hardcoded layer. Negative/NaN Y → layer 0.
pub fn world_pos_to_layer(y: f32) -> u8 {
    let max = LAYER_PROFILES.len().saturating_sub(1) as u8;
    ((y / LAYER_HEIGHT_M) as u8).min(max)
}

/// Snap a spawn position to a grid_gen-WALKABLE cell near `pos` (Y preserved). The phantom
/// collides + renders against grid_gen, but spawn positions come from `world::generator`'s player
/// spawn, which may land on a grid_gen wall → the phantom would spawn stuck. Tries the original
/// cell first, then a cross/ring of offsets (±2.5/5/7.5 m). Falls back to `pos` if none is
/// walkable (rare). Uses a throwaway cache (the PhantomDriver keeps its own for movement).
///
/// `rules_fn` must be the SAME resolutor the phantom's movement cache uses (ADR-033), or the snap
/// would land against a different world than the one the phantom then walks on.
pub fn resolve_spawn_near(seed: u64, pos: [f32; 3], rules_fn: RulesFn) -> [f32; 3] {
    const OFFSETS: [(f32, f32); 13] = [
        (0.0, 0.0), // original cell first, then a 12-step spiral (±2.5 cross, ±5 cross, ±5 diag)
        (2.5, 0.0),
        (0.0, 2.5),
        (-2.5, 0.0),
        (0.0, -2.5),
        (5.0, 0.0),
        (0.0, 5.0),
        (-5.0, 0.0),
        (0.0, -5.0),
        (5.0, 5.0),
        (-5.0, 5.0),
        (5.0, -5.0),
        (-5.0, -5.0),
    ];
    let mut cache = GridGenChunkCache::with_rules(seed, rules_fn);
    let layer = world_pos_to_layer(pos[1]);
    for (dx, dz) in OFFSETS {
        let cand = Vec3::new(pos[0] + dx, pos[1], pos[2] + dz);
        if is_walkable_grid_gen(&mut cache, cand, layer) {
            // ADR-040: return the CENTRE of the accepted cell, not the raw probe point. A spawn
            // sitting on a cell boundary makes the very first diagonal step ambiguous, and the
            // navigation plans from cell centres — starting off-centre would let a path begin with
            // a segment its own resolver rejects.
            let (gx, gz) = global_cell(cand);
            return [
                (gx as f32 + 0.5) * CELL_SIZE_M,
                pos[1],
                (gz as f32 + 0.5) * CELL_SIZE_M,
            ];
        }
    }
    pos // nothing walkable nearby → keep the original (rare)
}

/// True if `pos` falls in a walkable grid_gen cell of `layer`. Point sample at the position's
/// cell (per-frame phantom steps are < one 2.5 m cell, so the endpoint never skips a wall).
pub fn is_walkable_grid_gen(cache: &mut GridGenChunkCache, pos: Vec3, layer: u8) -> bool {
    let (gx, gz) = global_cell(pos);
    if cache.is_blocked_cell(gx, gz) {
        return false; // a player-built piece stands here (see `blocked_cells`)
    }
    let (cx, cz, cell_x, cell_z) = world_to_grid_cell(pos);
    cache
        .get_or_generate(cx, cz, layer)
        .get(cell_x, cell_z)
        .is_walkable()
}

/// ADR-040 amendment — the phantom stops being a dimensionless POINT and becomes a disc of this
/// radius. Without it the model can stand half-inside a wall panel: the point is legally on a
/// walkable cell while the visible body is not, which reads as clipping even though collision is
/// "correct". 0.5 m against a 2.5 m cell leaves 1.5 m of clearance in a one-cell corridor, so
/// corridors stay comfortably passable; what it does close are the diagonal pinch points.
pub const PHANTOM_BODY_RADIUS: f32 = 0.5;

/// Does the body fit here — centre plus the four cardinal extremes?
///
/// SAFETY VALVE: if the body does not fit where it ALREADY IS, this degrades to a point sample.
/// Otherwise a phantom that spawns (or is left by an earlier build) in a spot too tight for the new
/// radius would be fully blocked in every direction and freeze on the spot forever. Being generous
/// about leaving a bad position is always right; being generous about entering one is not.
fn body_fits(cache: &mut GridGenChunkCache, layer: u8, pos: Vec3, from_fits: bool) -> bool {
    if !is_walkable_grid_gen(cache, pos, layer) {
        return false;
    }
    if !from_fits {
        return true; // wedged: allow the point-level move so it can walk itself out
    }
    const R: f32 = PHANTOM_BODY_RADIUS;
    for (dx, dz) in [(R, 0.0), (-R, 0.0), (0.0, R), (0.0, -R)] {
        if !is_walkable_grid_gen(cache, Vec3::new(pos.x + dx, pos.y, pos.z + dz), layer) {
            return false;
        }
    }
    true
}

/// Resolve a move against grid_gen with axis sliding: try the full move, then X-only, then
/// Z-only, else stay. Horizontal-only: `from.y` is PRESERVED (the phantom keeps the Y it spawned
/// with, which is the player's spawn Y). `layer` selects which grid_gen layer's cells to test.
/// Mirrors the sliding of `resolve_move_simulated`, but reads grid_gen cells instead of
/// `ChunkLayoutV1`.
pub fn resolve_move_grid_gen(
    cache: &mut GridGenChunkCache,
    layer: u8,
    from: Vec3,
    desired: Vec3,
) -> Vec3 {
    resolve_move_grid_gen_ex(cache, layer, from, desired).pos
}

/// Outcome of a resolved move. ADR-040: `blocked` exists because STALK and SPRINT never noticed
/// they had been stopped — only WANDER did — so the phantom ground into walls while chasing. It is
/// the trigger the navigation uses to replan instead of stalling.
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct MoveResult {
    pub pos: Vec3,
    /// Fully blocked: the phantom did not move at all this step.
    pub blocked: bool,
    /// Moved, but only along one axis — the diagonal or the full step was refused.
    pub slid: bool,
}

/// Same as `resolve_move_grid_gen`, but reports HOW the move resolved.
pub fn resolve_move_grid_gen_ex(
    cache: &mut GridGenChunkCache,
    layer: u8,
    from: Vec3,
    desired: Vec3,
) -> MoveResult {
    // Preserve the phantom's current Y: horizontal movement must not change height. The Y is set
    // correctly at spawn (near the player); only X/Z slide against geometry.
    let y = from.y;
    let full = Vec3::new(desired.x, y, desired.z);
    // ADR-040: the destination cell being walkable is NOT enough for a diagonal step — the cell the
    // segment actually passes through has to be walkable too.
    // Whether the body fits where it currently stands decides how strict we may be (see body_fits).
    let from_fits = body_fits(cache, layer, from, true);
    if !from_fits {
        // ADR-043 instrumentation: the safety valve is engaged for this whole resolve, so the body
        // radius is off and the creature is moving as a point. Counted, not logged, because it can
        // fire many times a second — the throttled step report reads the counter.
        cache.degraded_body_checks += 1;
    }
    let (pos, blocked, slid) = if body_fits(cache, layer, full, from_fits)
        && diagonal_step_is_clear(cache, layer, from, full)
    {
        (full, false, false)
    } else {
        let x_only = Vec3::new(desired.x, y, from.z);
        if body_fits(cache, layer, x_only, from_fits) {
            (x_only, false, true)
        } else {
            let z_only = Vec3::new(from.x, y, desired.z);
            if body_fits(cache, layer, z_only, from_fits) {
                (z_only, false, true)
            } else {
                (Vec3::new(from.x, y, from.z), true, false) // fully blocked → stay
            }
        }
    };
    let center = (
        (from.x / CHUNK_SIZE_M).floor() as i32,
        (from.z / CHUNK_SIZE_M).floor() as i32,
    );
    cache.enforce_cap(center);
    MoveResult { pos, blocked, slid }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::world::grid_gen::{Cell, CellType};

    fn cache_with_grid(grid: LayerGrid) -> GridGenChunkCache {
        let mut c = GridGenChunkCache::new(1);
        c.cache.insert((0, 0, 0), grid);
        c
    }

    fn cell_center(cell_x: usize, cell_z: usize) -> Vec3 {
        Vec3::new(
            cell_x as f32 * CELL_SIZE_M + CELL_SIZE_M * 0.5,
            grid_floor_y(0),
            cell_z as f32 * CELL_SIZE_M + CELL_SIZE_M * 0.5,
        )
    }

    /// ADR-043 — the cache budget (~420 KB at 256 entries) is arithmetic over `size_of::<Cell>()`,
    /// and `Cell` is `repr(Rust)`: the compiler owes us nothing about its layout. Pin it, so that
    /// growing `Cell` shows up here as a failing budget rather than as silent memory growth.
    #[test]
    fn cell_is_four_bytes_so_the_cache_budget_holds() {
        assert_eq!(
            std::mem::size_of::<Cell>(),
            4,
            "Cell grew; re-derive the cache budget"
        );
        let per_layer = std::mem::size_of::<Cell>() * CHUNK_CELLS * CHUNK_CELLS;
        assert_eq!(per_layer, 1600);
        // Heap held by a full cache, ignoring per-entry table overhead (~40 B each).
        assert!(
            per_layer * GRID_CACHE_MAX_CHUNKS < 512 * 1024,
            "full cache is {} B, over the half-megabyte the ADR budgets",
            per_layer * GRID_CACHE_MAX_CHUNKS
        );
    }

    /// ADR-043 — THE reason the cap moved. Several movers scattered across the map must be able to
    /// hold their working sets AT THE SAME TIME. `enforce_cap` evicts by distance from a single
    /// `center` (the mover that just acted), so once the combined working set exceeds the cap each
    /// mover throws away the previous one's chunks and every step pays full generation again.
    ///
    /// The assert is on `generated_count`, not on `len()`: a thrashing cache sits at exactly its
    /// cap too, so its size looks identical to a healthy one. Only the regeneration counter can
    /// tell them apart. Mutation check: with the old cap of 64 the second round regenerates.
    #[test]
    fn scattered_movers_keep_their_working_sets_without_mutual_eviction() {
        let mut cache = GridGenChunkCache::new(42);
        // 8 movers, 20 chunks (1 km) apart, so no two working sets overlap at all.
        let movers: Vec<(i32, i32)> = (0..8).map(|i| (i * 20, i * 20)).collect();
        // A mover's per-step footprint: the 4×4 chunk block its A* window can span.
        let touch = |cache: &mut GridGenChunkCache, (mcx, mcz): (i32, i32)| {
            for dx in 0..4 {
                for dz in 0..4 {
                    cache.get_or_generate(mcx + dx, mcz + dz, 0);
                }
            }
            cache.enforce_cap((mcx, mcz));
        };

        for m in &movers {
            touch(&mut cache, *m);
        }
        let after_warmup = cache.generated_count();
        assert_eq!(
            after_warmup,
            8 * 16,
            "warm-up must generate each chunk once"
        );

        // Second round: everything is already cached, so a cache that is not evicting its own
        // tenants generates NOTHING.
        for m in &movers {
            touch(&mut cache, *m);
        }
        assert_eq!(
            cache.generated_count(),
            after_warmup,
            "scattered movers are evicting each other: {} regenerations in a warm cache",
            cache.generated_count() - after_warmup
        );
        assert!(cache.len() <= GRID_CACHE_MAX_CHUNKS);
    }

    #[test]
    fn is_walkable_false_on_solid_true_on_open() {
        let mut grid = LayerGrid::new_solid(); // all Wall (solid)
        grid.set(5, 5, Cell::new(CellType::Corridor, 2, 0)); // one walkable cell
        let mut c = cache_with_grid(grid);
        assert!(
            is_walkable_grid_gen(&mut c, cell_center(5, 5), 0),
            "open cell must be walkable"
        );
        assert!(
            !is_walkable_grid_gen(&mut c, cell_center(4, 5), 0),
            "solid cell must block"
        );
    }

    #[test]
    fn resolve_move_does_not_enter_solid_cell() {
        let mut grid = LayerGrid::new_solid();
        grid.set(4, 5, Cell::new(CellType::Corridor, 2, 0)); // start cell; (5,5) stays solid
        let mut c = cache_with_grid(grid);
        let from = cell_center(4, 5);
        let into_solid = cell_center(5, 5); // SOLID neighbour
        let result = resolve_move_grid_gen(&mut c, 0, from, into_solid);
        assert!(
            is_walkable_grid_gen(&mut c, result, 0),
            "resolved pos must be walkable (never inside the wall cell)"
        );
    }

    /// ADR-040 D-DIAGONAL — THE repro. Two walkable cells touching only at a corner, both
    /// intermediates solid. Before the fix the destination-only sample accepted this step and the
    /// phantom crossed the wall; this is the "atraviesa paredes" the play-test reported.
    #[test]
    fn diagonal_step_through_solid_cell_is_blocked() {
        let mut grid = LayerGrid::new_solid();
        grid.set(4, 4, Cell::new(CellType::Corridor, 2, 0));
        grid.set(5, 5, Cell::new(CellType::Corridor, 2, 0));
        // (5,4) and (4,5) stay SOLID → the only way across is through a wall.
        let mut c = cache_with_grid(grid);

        // Start off-centre so the segment is unambiguously diagonal, and try both a slow (0.30 m)
        // and a sprint-sized (0.90 m) step.
        let from = Vec3::new(12.4, grid_floor_y(0), 12.4);
        for step in [0.30_f32, 0.90] {
            let desired = Vec3::new(from.x + step, from.y, from.z + step);
            let r = resolve_move_grid_gen_ex(&mut c, 0, from, desired);
            assert!(
                r.blocked,
                "diagonal through a solid corner must be refused (step {step}), got {:?}",
                r.pos
            );
            assert_eq!(r.pos, from, "a refused step must not move the phantom");
        }
    }

    /// The mirror test, and the reason the rule is exact instead of conservative: cutting a CONVEX
    /// corner is legal and must stay legal. Without this, a stricter rule would sail through review
    /// and the creature would only ever move in a cross pattern.
    #[test]
    fn diagonal_around_convex_corner_still_allowed() {
        let mut grid = LayerGrid::new_solid();
        grid.set(4, 4, Cell::new(CellType::Corridor, 2, 0));
        grid.set(5, 5, Cell::new(CellType::Corridor, 2, 0));
        grid.set(5, 4, Cell::new(CellType::Corridor, 2, 0)); // the +X intermediate is OPEN
        let mut c = cache_with_grid(grid);

        // Cross the X boundary first (larger dx than dz) → the segment passes through (5,4).
        let from = Vec3::new(12.4, grid_floor_y(0), 12.4);
        let desired = Vec3::new(12.6, from.y, 12.55);
        let r = resolve_move_grid_gen_ex(&mut c, 0, from, desired);
        assert!(
            !r.blocked,
            "a diagonal through an OPEN intermediate must be allowed"
        );
        assert!(
            !r.slid,
            "it must be taken in full, not degraded to an axial slide"
        );
        assert_eq!(r.pos, Vec3::new(desired.x, from.y, desired.z));
    }

    /// Freezes the assumption that makes the two-cell reasoning COMPLETE: a phantom step is shorter
    /// than one cell, so it crosses at most one boundary per axis. If someone raises the sprint
    /// speed or the entity tick period, this fails instead of silently reopening the tunnelling
    /// hole the diagonal rule does not cover.
    #[test]
    fn max_phantom_step_stays_under_one_cell() {
        const PHANTOM_SPRINT_SPEED: f32 = 9.0; // game_loop.rs
        const ENTITY_DT: f32 = 6.0 / 60.0; // ENTITY_TICK_EVERY / TICK_HZ
        let step = PHANTOM_SPRINT_SPEED * ENTITY_DT;
        assert!(
            step < CELL_SIZE_M,
            "max step {step} m must stay under one {CELL_SIZE_M} m cell"
        );
    }

    /// Critical regression: the diagonal rule must not break wall-sliding. A phantom pressed
    /// against a wall still has to travel along it, or it reads as stuck.
    #[test]
    fn resolve_move_still_slides_along_a_wall() {
        let mut grid = LayerGrid::new_solid();
        for z in 3..8 {
            grid.set(4, z, Cell::new(CellType::Corridor, 2, 0)); // open corridor along Z
        }
        let mut c = cache_with_grid(grid);
        let from = cell_center(4, 5);
        // Push diagonally into the solid +X neighbour: X must be refused, Z must still advance.
        let desired = Vec3::new(from.x + 1.5, from.y, from.z + 0.5);
        let r = resolve_move_grid_gen_ex(&mut c, 0, from, desired);
        assert!(
            !r.blocked,
            "must not be fully blocked — sliding along Z is available"
        );
        assert!(r.slid, "the move must be reported as a slide");
        assert!(
            (r.pos.z - desired.z).abs() < 1e-4 && (r.pos.x - from.x).abs() < 1e-4,
            "expected Z-only slide, got {:?}",
            r.pos
        );
    }

    /// A player-built piece must stop the phantom even though the GENERATOR calls that cell open.
    /// Walking through a wall you just built to hide behind is the failure that reads as the game
    /// being broken rather than as the creature being frightening.
    #[test]
    fn a_built_piece_blocks_a_cell_the_generator_calls_open() {
        let mut grid = LayerGrid::new_solid();
        for x in 3..8 {
            grid.set(x, 5, Cell::new(CellType::Corridor, 2, 0));
        }
        let mut c = cache_with_grid(grid);
        let from = cell_center(4, 5);
        let desired = Vec3::new(from.x + 0.9, from.y, from.z);

        // Open corridor: the step is taken.
        let before = resolve_move_grid_gen_ex(&mut c, 0, from, desired);
        assert!(
            before.pos.x > from.x,
            "the corridor must be walkable to begin with"
        );

        // Build a piece in the next cell along.
        let mut blocked = std::collections::HashSet::new();
        blocked.insert(global_cell(Vec3::new(from.x + 2.5, from.y, from.z)));
        c.set_blocked_cells(blocked);

        let after = resolve_move_grid_gen_ex(&mut c, 0, from, desired);
        assert!(
            (after.pos.x - from.x).abs() < 1e-4,
            "a built piece must stop it, but it moved to {:?}",
            after.pos
        );
        assert_eq!(c.blocked_cell_count(), 1);
    }

    /// The body radius must NOT seal a one-cell corridor. 0.5 m against a 2.5 m cell leaves 1.5 m
    /// of clearance, but that is an argument, not a guarantee — this walks a corridor end to end.
    #[test]
    fn body_radius_does_not_seal_a_one_cell_corridor() {
        let mut grid = LayerGrid::new_solid();
        for z in 2..12 {
            grid.set(4, z, Cell::new(CellType::Corridor, 2, 0));
        }
        let mut c = cache_with_grid(grid);
        let mut pos = cell_center(4, 3);
        for _ in 0..200 {
            let desired = Vec3::new(pos.x, pos.y, pos.z + 0.9); // sprint-sized step along the corridor
            let r = resolve_move_grid_gen_ex(&mut c, 0, pos, desired);
            assert!(
                !r.blocked,
                "the corridor must stay walkable, stuck at {pos:?}"
            );
            pos = r.pos;
            if pos.z >= cell_center(4, 10).z {
                return; // walked the length of it
            }
        }
        panic!("never reached the far end, stopped at {pos:?}");
    }

    /// The safety valve. A phantom standing somewhere the disc does not fit must still be able to
    /// move OUT; otherwise the radius change would freeze anything left in a tight spot.
    #[test]
    fn a_wedged_body_can_still_walk_itself_out() {
        let mut grid = LayerGrid::new_solid();
        grid.set(5, 5, Cell::new(CellType::Corridor, 2, 0)); // a single isolated open cell…
        for z in 5..12 {
            grid.set(6, z, Cell::new(CellType::Corridor, 2, 0)); // …with an exit to +X
        }
        let mut c = cache_with_grid(grid);
        let from = cell_center(5, 5); // the disc cannot fit here: neighbours are solid
        let desired = Vec3::new(from.x + 0.9, from.y, from.z);
        let r = resolve_move_grid_gen_ex(&mut c, 0, from, desired);
        assert!(
            !r.blocked,
            "a wedged phantom must degrade to point collision and be able to leave"
        );
        assert!(r.pos.x > from.x, "it must actually move toward the exit");
    }

    /// ADR-040: a spawn must land on the cell CENTRE, so the first step is never an ambiguous
    /// boundary case and the navigation can plan from it.
    #[test]
    fn spawn_snaps_to_cell_center() {
        let pos = Vec3::new(12.4, grid_floor_y(0), 12.4);
        let (gx, gz) = global_cell(pos);
        let expected_x = (gx as f32 + 0.5) * CELL_SIZE_M;
        let expected_z = (gz as f32 + 0.5) * CELL_SIZE_M;
        let out = resolve_spawn_near(42, pos.to_array(), default_layer_rules);
        // Whichever offset the spiral accepts, the result must be a cell centre.
        let (ogx, ogz) = global_cell(Vec3::new(out[0], out[1], out[2]));
        assert!(
            (out[0] - (ogx as f32 + 0.5) * CELL_SIZE_M).abs() < 1e-3
                && (out[2] - (ogz as f32 + 0.5) * CELL_SIZE_M).abs() < 1e-3,
            "spawn must sit at a cell centre, got ({}, {}) — nearest centre of its own cell is ({}, {})",
            out[0],
            out[2],
            expected_x,
            expected_z
        );
    }

    #[test]
    fn grid_floor_y_matches_render_layer_pitch() {
        // The floor plane must equal Unity's rendered pitch (layer * LayerHeight = 4 m): 0/4/8/12.
        assert_eq!(grid_floor_y(0), 0.0);
        assert_eq!(grid_floor_y(1), 4.0);
        assert_eq!(grid_floor_y(2), 8.0);
        assert_eq!(grid_floor_y(3), 12.0);
    }

    #[test]
    fn resolve_move_preserves_from_y() {
        // Horizontal-only: the resolved pose keeps from.y (no floor pin), so the phantom holds the
        // height it spawned at instead of snapping/floating.
        let mut grid = LayerGrid::new_solid();
        grid.set(5, 5, Cell::new(CellType::Corridor, 2, 0));
        let mut c = cache_with_grid(grid);
        let from = Vec3::new(cell_center(5, 5).x, 6.4, cell_center(5, 5).z); // arbitrary Y
        let result = resolve_move_grid_gen(&mut c, 0, from, from);
        assert!(
            (result.y - 6.4).abs() < 1e-4,
            "resolve must preserve from.y, got {}",
            result.y
        );
    }

    #[test]
    fn world_pos_to_layer_maps_y_to_macro_layer() {
        assert_eq!(world_pos_to_layer(0.0), 0);
        assert_eq!(world_pos_to_layer(1.8), 0); // standing on layer 0
        assert_eq!(world_pos_to_layer(4.0), 1);
        assert_eq!(world_pos_to_layer(8.0), 2);
        assert_eq!(world_pos_to_layer(12.0), 3);
        assert_eq!(world_pos_to_layer(99.0), 3); // clamps to the top layer
        assert_eq!(world_pos_to_layer(-5.0), 0); // negative clamps to 0
    }

    #[test]
    fn resolve_spawn_near_lands_walkable_or_falls_back_keeping_y() {
        let seed = 42;
        let input = [27.5_f32, 1.8, 27.5];
        let r = resolve_spawn_near(seed, input, default_layer_rules);
        assert!((r[1] - input[1]).abs() < 1e-4, "Y must be preserved");
        // The result is either a walkable grid_gen cell or the original fallback.
        let mut c = GridGenChunkCache::new(seed);
        let walkable = is_walkable_grid_gen(&mut c, Vec3::new(r[0], r[1], r[2]), 0);
        assert!(
            walkable || r == input,
            "result must be walkable or the original fallback"
        );
    }

    /// Perfil de prueba con densidad de salón-con-pilares. LOCAL a propósito: el
    /// resolutor real vive en `world::zone_density` y `grid_gen` no importa
    /// `world/` ni en tests. Aquí se prueba el MECANISMO (la caché honra
    /// `rules_fn`); la coincidencia con el resolutor real de ADR-033 se prueba en
    /// `world::zone_density::tests::render_and_phantom_agree_on_pillar_hall`.
    fn pillar_hall_like_rules(_seed: u64, _cx: i32, _cz: i32, layer: u8) -> LayerRules {
        let mut rules = LAYER_PROFILES[(layer as usize).min(LAYER_PROFILES.len() - 1)].clone();
        rules.num_open_zones = 4;
        rules.open_zone_size = 7;
        rules.pillar_chance = 0.6;
        rules
    }

    #[test]
    fn grid_cache_layout_matches_direct_generation() {
        // The cache must generate the SAME grid the render derives from (zero world divergence).
        let mut c = GridGenChunkCache::new(42);
        let pos = (3, -7);
        let cached = c.get_or_generate(pos.0, pos.1, 0).cells().to_vec();
        let rules = &LAYER_PROFILES[0];
        let direct = generate_chunk_layer(rules, 42, pos, 0, &[]);
        assert_eq!(
            cached.as_slice(),
            direct.grid.cells(),
            "cache layout must equal direct generation"
        );

        // ADR-033: la identidad debe sostenerse también cuando el perfil NO es el
        // plano de capa — es el caso nuevo que introduce la densidad por zona.
        let mut zoned = GridGenChunkCache::with_rules(42, pillar_hall_like_rules);
        let zoned_cached = zoned.get_or_generate(pos.0, pos.1, 0).cells().to_vec();
        let zoned_direct = generate_chunk_layer(
            &pillar_hall_like_rules(42, pos.0, pos.1, 0),
            42,
            pos,
            0,
            &[],
        );
        assert_eq!(
            zoned_cached.as_slice(),
            zoned_direct.grid.cells(),
            "cache layout must equal direct generation con perfil por zona"
        );
        // Y el caso zonificado tiene que ser REALMENTE distinto del plano, o la
        // aserción de arriba sería vacía.
        assert_ne!(
            zoned_cached, cached,
            "el perfil de zona no cambió el grid — el test no estaría probando nada"
        );
    }
}
