//! ADR-016/017 follow-up — phantom collision against the GRID_GEN world (the world Unity
//! actually renders), replacing the historical world::generator path.
//!
//! The robapieles previously collided against `world::generator`'s `ChunkLayoutV1`, a DIFFERENT
//! generator from grid_gen. Since Unity renders grid_gen (via `tile_walls` → IPC chunk stream →
//! `GridChunkBuilder`), the phantom phased through visible walls and snagged on invisible ones.
//! This module resolves the phantom's movement against grid_gen's own 20×20 cell grid, generated
//! by the SAME deterministic path the render uses, so collision matches what the player sees.
//!
//! Host-only, on-demand, bounded cache; NEVER serialized to Unity and NEVER inserted into
//! `world.chunks`. The player collision path (`world::collision`) is untouched.
//!
//! GRANULARITY NOTE (D-colisión = (a) raw cells): this samples raw 2.5 m grid_gen cells
//! (`Cell::is_walkable`), which share the GENERATOR with the render but not its exact tile-walls
//! model (5 m tiles, every tile floored, walls only on the `tile_walls` bitmask edges). It removes
//! the wrong-WORLD mismatch; a small residual cell-vs-tile mismatch remains until/if collision
//! moves to the `tile_walls` bitmask (option (b), deferred).

use std::collections::HashMap;

use crate::utils::Vec3;

use super::{
    generate_chunk_layer, LayerGrid, LayerRules, CELL_SIZE_M, CHUNK_CELLS, LAYER_HEIGHT_M,
    LAYER_PROFILES,
};

/// World-units per chunk side (20 cells × 2.5 m = 50 m).
const CHUNK_SIZE_M: f32 = CELL_SIZE_M * CHUNK_CELLS as f32;
/// Max live cached grid_gen layouts; farthest-from-query eviction (mirrors `SimChunkCache`).
pub const GRID_CACHE_MAX_CHUNKS: usize = 64;

/// Host-only, on-demand cache of grid_gen `LayerGrid`s for phantom collision. Generated by the
/// SAME deterministic call the render uses (`generate_chunk_layer(..., &[])`), so the phantom
/// collides against the geometry the player sees. Never serialized, never in `world.chunks`.
pub struct GridGenChunkCache {
    seed: u64,
    cache: HashMap<(i32, i32, u8), LayerGrid>,
    rules_fn: RulesFn,
}

/// Resolutor de perfil por chunk: `(world_seed, cx, cz, layer) → LayerRules`.
///
/// ADR-033 inyecta aquí `world::zone_density::rules_for` (que deriva el perfil
/// del `zone_kind` del chunk) SIN que `grid_gen` importe `world/` — la
/// invariante del módulo se conserva porque grid_gen solo conoce la FIRMA, no
/// la implementación ni el concepto de zona.
pub type RulesFn = fn(u64, i32, i32, u8) -> LayerRules;

/// Resolutor por defecto: perfil de capa, el comportamiento pre-ADR-033.
///
/// Solo para consumidores que deliberadamente no quieren densidad por zona
/// (tests de generación pura). Las rutas de RENDER y ROBAPIELES deben inyectar
/// el resolutor real: si una usa este y la otra no, render y colisión divergen
/// — exactamente lo que ADR-033 promete que no pasa.
pub fn default_layer_rules(_seed: u64, _cx: i32, _cz: i32, layer: u8) -> LayerRules {
    LAYER_PROFILES[(layer as usize).min(LAYER_PROFILES.len() - 1)].clone()
}

impl GridGenChunkCache {
    /// Caché con el perfil de capa plano (sin densidad por zona).
    pub fn new(seed: u64) -> Self {
        Self::with_rules(seed, default_layer_rules)
    }

    /// Caché con resolutor de perfil explícito (ADR-033).
    pub fn with_rules(seed: u64, rules_fn: RulesFn) -> Self {
        Self {
            seed,
            cache: HashMap::new(),
            rules_fn,
        }
    }

    pub fn len(&self) -> usize {
        self.cache.len()
    }

    pub fn is_empty(&self) -> bool {
        self.cache.is_empty()
    }

    /// The grid_gen `LayerGrid` for (cx, cz, layer), generated on first access with the same
    /// generator + EMPTY `forced_walkable` that `chunk_tile_walls` uses — so the cached grid is
    /// byte-identical to the rendered chunk's source. Since ADR-033 that identity ALSO requires
    /// the same `rules_fn` as the render path: `grid_cache_layout_matches_direct_generation`
    /// guards it.
    pub fn get_or_generate(&mut self, cx: i32, cz: i32, layer: u8) -> &LayerGrid {
        // Single hash lookup per access (was contains_key + insert + get = 3).
        let seed = self.seed;
        let rules_fn = self.rules_fn;
        self.cache.entry((cx, cz, layer)).or_insert_with(|| {
            let rules = rules_fn(seed, cx, cz, layer);
            generate_chunk_layer(&rules, seed, (cx, cz), layer as i32, &[]).grid
        })
    }

    /// Evict the farthest-from-`center` (Chebyshev) layouts until within the cap. The current
    /// move's working set sits closest to `center`, so it is never evicted.
    pub fn enforce_cap(&mut self, center: (i32, i32)) {
        while self.cache.len() > GRID_CACHE_MAX_CHUNKS {
            let farthest = self
                .cache
                .keys()
                .max_by_key(|(cx, cz, _)| (cx - center.0).abs().max((cz - center.1).abs()))
                .copied();
            match farthest {
                Some(k) => {
                    self.cache.remove(&k);
                }
                None => break,
            }
        }
    }
}

/// World XZ → (chunk_x, chunk_z, cell_x, cell_z) in grid_gen coords. Floor division handles
/// negative world coordinates; the cell is clamped into the 20×20 grid.
fn world_to_grid_cell(pos: Vec3) -> (i32, i32, usize, usize) {
    let cx = (pos.x / CHUNK_SIZE_M).floor() as i32;
    let cz = (pos.z / CHUNK_SIZE_M).floor() as i32;
    let local_x = pos.x - cx as f32 * CHUNK_SIZE_M;
    let local_z = pos.z - cz as f32 * CHUNK_SIZE_M;
    let max = CHUNK_CELLS as i32 - 1;
    let cell_x = ((local_x / CELL_SIZE_M).floor() as i32).clamp(0, max) as usize;
    let cell_z = ((local_z / CELL_SIZE_M).floor() as i32).clamp(0, max) as usize;
    (cx, cz, cell_x, cell_z)
}

/// Floor-plane Y of a grid_gen `layer` — the SAME pitch Unity renders (layer 0 = 0, layer 1 = 4,
/// layer 2 = 8, …).
pub fn grid_floor_y(layer: u8) -> f32 {
    layer as f32 * LAYER_HEIGHT_M
}

/// World Y → the macro layer that Y stands on (inverse of the layer pitch), clamped to the valid
/// layer range. Used to pick which grid_gen layer's cells a phantom collides against, derived from
/// its own pose Y so it works on every layer without a hardcoded layer. Negative/NaN Y → layer 0.
pub fn world_pos_to_layer(y: f32) -> u8 {
    let max = LAYER_PROFILES.len().saturating_sub(1) as u8;
    ((y / LAYER_HEIGHT_M) as u8).min(max)
}

/// Snap a spawn position to a grid_gen-WALKABLE cell near `pos` (Y preserved). The phantom
/// collides + renders against grid_gen, but spawn positions come from `world::generator`'s player
/// spawn, which may land on a grid_gen wall → the phantom would spawn stuck. Tries the original
/// cell first, then a cross/ring of offsets (±2.5/5/7.5 m). Falls back to `pos` if none is
/// walkable (rare). Uses a throwaway cache (the PhantomDriver keeps its own for movement).
///
/// `rules_fn` must be the SAME resolutor the phantom's movement cache uses (ADR-033), or the snap
/// would land against a different world than the one the phantom then walks on.
pub fn resolve_spawn_near(seed: u64, pos: [f32; 3], rules_fn: RulesFn) -> [f32; 3] {
    const OFFSETS: [(f32, f32); 13] = [
        (0.0, 0.0), // original cell first, then a 12-step spiral (±2.5 cross, ±5 cross, ±5 diag)
        (2.5, 0.0),
        (0.0, 2.5),
        (-2.5, 0.0),
        (0.0, -2.5),
        (5.0, 0.0),
        (0.0, 5.0),
        (-5.0, 0.0),
        (0.0, -5.0),
        (5.0, 5.0),
        (-5.0, 5.0),
        (5.0, -5.0),
        (-5.0, -5.0),
    ];
    let mut cache = GridGenChunkCache::with_rules(seed, rules_fn);
    let layer = world_pos_to_layer(pos[1]);
    for (dx, dz) in OFFSETS {
        let cand = Vec3::new(pos[0] + dx, pos[1], pos[2] + dz);
        if is_walkable_grid_gen(&mut cache, cand, layer) {
            return cand.to_array();
        }
    }
    pos // nothing walkable nearby → keep the original (rare)
}

/// True if `pos` falls in a walkable grid_gen cell of `layer`. Point sample at the position's
/// cell (per-frame phantom steps are < one 2.5 m cell, so the endpoint never skips a wall).
pub fn is_walkable_grid_gen(cache: &mut GridGenChunkCache, pos: Vec3, layer: u8) -> bool {
    let (cx, cz, cell_x, cell_z) = world_to_grid_cell(pos);
    cache
        .get_or_generate(cx, cz, layer)
        .get(cell_x, cell_z)
        .is_walkable()
}

/// Resolve a move against grid_gen with axis sliding: try the full move, then X-only, then
/// Z-only, else stay. Horizontal-only: `from.y` is PRESERVED (the phantom keeps the Y it spawned
/// with, which is the player's spawn Y). `layer` selects which grid_gen layer's cells to test.
/// Mirrors the sliding of `resolve_move_simulated`, but reads grid_gen cells instead of
/// `ChunkLayoutV1`.
pub fn resolve_move_grid_gen(
    cache: &mut GridGenChunkCache,
    layer: u8,
    from: Vec3,
    desired: Vec3,
) -> Vec3 {
    // Preserve the phantom's current Y: horizontal movement must not change height. The Y is set
    // correctly at spawn (near the player); only X/Z slide against geometry.
    let y = from.y;
    let full = Vec3::new(desired.x, y, desired.z);
    let result = if is_walkable_grid_gen(cache, full, layer) {
        full
    } else {
        let x_only = Vec3::new(desired.x, y, from.z);
        if is_walkable_grid_gen(cache, x_only, layer) {
            x_only
        } else {
            let z_only = Vec3::new(from.x, y, desired.z);
            if is_walkable_grid_gen(cache, z_only, layer) {
                z_only
            } else {
                Vec3::new(from.x, y, from.z) // fully blocked → stay
            }
        }
    };
    let center = (
        (from.x / CHUNK_SIZE_M).floor() as i32,
        (from.z / CHUNK_SIZE_M).floor() as i32,
    );
    cache.enforce_cap(center);
    result
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::world::grid_gen::{Cell, CellType};

    fn cache_with_grid(grid: LayerGrid) -> GridGenChunkCache {
        let mut c = GridGenChunkCache::new(1);
        c.cache.insert((0, 0, 0), grid);
        c
    }

    fn cell_center(cell_x: usize, cell_z: usize) -> Vec3 {
        Vec3::new(
            cell_x as f32 * CELL_SIZE_M + CELL_SIZE_M * 0.5,
            grid_floor_y(0),
            cell_z as f32 * CELL_SIZE_M + CELL_SIZE_M * 0.5,
        )
    }

    #[test]
    fn is_walkable_false_on_solid_true_on_open() {
        let mut grid = LayerGrid::new_solid(); // all Wall (solid)
        grid.set(5, 5, Cell::new(CellType::Corridor, 2, 0)); // one walkable cell
        let mut c = cache_with_grid(grid);
        assert!(
            is_walkable_grid_gen(&mut c, cell_center(5, 5), 0),
            "open cell must be walkable"
        );
        assert!(
            !is_walkable_grid_gen(&mut c, cell_center(4, 5), 0),
            "solid cell must block"
        );
    }

    #[test]
    fn resolve_move_does_not_enter_solid_cell() {
        let mut grid = LayerGrid::new_solid();
        grid.set(4, 5, Cell::new(CellType::Corridor, 2, 0)); // start cell; (5,5) stays solid
        let mut c = cache_with_grid(grid);
        let from = cell_center(4, 5);
        let into_solid = cell_center(5, 5); // SOLID neighbour
        let result = resolve_move_grid_gen(&mut c, 0, from, into_solid);
        assert!(
            is_walkable_grid_gen(&mut c, result, 0),
            "resolved pos must be walkable (never inside the wall cell)"
        );
    }

    #[test]
    fn grid_floor_y_matches_render_layer_pitch() {
        // The floor plane must equal Unity's rendered pitch (layer * LayerHeight = 4 m): 0/4/8/12.
        assert_eq!(grid_floor_y(0), 0.0);
        assert_eq!(grid_floor_y(1), 4.0);
        assert_eq!(grid_floor_y(2), 8.0);
        assert_eq!(grid_floor_y(3), 12.0);
    }

    #[test]
    fn resolve_move_preserves_from_y() {
        // Horizontal-only: the resolved pose keeps from.y (no floor pin), so the phantom holds the
        // height it spawned at instead of snapping/floating.
        let mut grid = LayerGrid::new_solid();
        grid.set(5, 5, Cell::new(CellType::Corridor, 2, 0));
        let mut c = cache_with_grid(grid);
        let from = Vec3::new(cell_center(5, 5).x, 6.4, cell_center(5, 5).z); // arbitrary Y
        let result = resolve_move_grid_gen(&mut c, 0, from, from);
        assert!(
            (result.y - 6.4).abs() < 1e-4,
            "resolve must preserve from.y, got {}",
            result.y
        );
    }

    #[test]
    fn world_pos_to_layer_maps_y_to_macro_layer() {
        assert_eq!(world_pos_to_layer(0.0), 0);
        assert_eq!(world_pos_to_layer(1.8), 0); // standing on layer 0
        assert_eq!(world_pos_to_layer(4.0), 1);
        assert_eq!(world_pos_to_layer(8.0), 2);
        assert_eq!(world_pos_to_layer(12.0), 3);
        assert_eq!(world_pos_to_layer(99.0), 3); // clamps to the top layer
        assert_eq!(world_pos_to_layer(-5.0), 0); // negative clamps to 0
    }

    #[test]
    fn resolve_spawn_near_lands_walkable_or_falls_back_keeping_y() {
        let seed = 42;
        let input = [27.5_f32, 1.8, 27.5];
        let r = resolve_spawn_near(seed, input, default_layer_rules);
        assert!((r[1] - input[1]).abs() < 1e-4, "Y must be preserved");
        // The result is either a walkable grid_gen cell or the original fallback.
        let mut c = GridGenChunkCache::new(seed);
        let walkable = is_walkable_grid_gen(&mut c, Vec3::new(r[0], r[1], r[2]), 0);
        assert!(
            walkable || r == input,
            "result must be walkable or the original fallback"
        );
    }

    /// Perfil de prueba con densidad de salón-con-pilares. LOCAL a propósito: el
    /// resolutor real vive en `world::zone_density` y `grid_gen` no importa
    /// `world/` ni en tests. Aquí se prueba el MECANISMO (la caché honra
    /// `rules_fn`); la coincidencia con el resolutor real de ADR-033 se prueba en
    /// `world::zone_density::tests::render_and_phantom_agree_on_pillar_hall`.
    fn pillar_hall_like_rules(_seed: u64, _cx: i32, _cz: i32, layer: u8) -> LayerRules {
        let mut rules = LAYER_PROFILES[(layer as usize).min(LAYER_PROFILES.len() - 1)].clone();
        rules.num_open_zones = 4;
        rules.open_zone_size = 7;
        rules.pillar_chance = 0.6;
        rules
    }

    #[test]
    fn grid_cache_layout_matches_direct_generation() {
        // The cache must generate the SAME grid the render derives from (zero world divergence).
        let mut c = GridGenChunkCache::new(42);
        let pos = (3, -7);
        let cached = c.get_or_generate(pos.0, pos.1, 0).cells().to_vec();
        let rules = &LAYER_PROFILES[0];
        let direct = generate_chunk_layer(rules, 42, pos, 0, &[]);
        assert_eq!(
            cached.as_slice(),
            direct.grid.cells(),
            "cache layout must equal direct generation"
        );

        // ADR-033: la identidad debe sostenerse también cuando el perfil NO es el
        // plano de capa — es el caso nuevo que introduce la densidad por zona.
        let mut zoned = GridGenChunkCache::with_rules(42, pillar_hall_like_rules);
        let zoned_cached = zoned.get_or_generate(pos.0, pos.1, 0).cells().to_vec();
        let zoned_direct = generate_chunk_layer(
            &pillar_hall_like_rules(42, pos.0, pos.1, 0),
            42,
            pos,
            0,
            &[],
        );
        assert_eq!(
            zoned_cached.as_slice(),
            zoned_direct.grid.cells(),
            "cache layout must equal direct generation con perfil por zona"
        );
        // Y el caso zonificado tiene que ser REALMENTE distinto del plano, o la
        // aserción de arriba sería vacía.
        assert_ne!(
            zoned_cached, cached,
            "el perfil de zona no cambió el grid — el test no estaría probando nada"
        );
    }
}
